### ISSUE TITLE
Ocr

### ISSUE THREAD

**Issue by joeblew99** [milosgajdos83/gopfield#4]
I am trying :) to build a 100% golang based ice system.

Hopfield RNA would be a good basis ?

**Comment by joeblew99** [comment]
Sorry i on on mobile. I meant to say OCR system.

Read a page of text as an image.
Isolate all the letters locations.
Compute matches with confidence score.
Output a map of letters and their locations on the original image.

I need to probably add some sort of algo to then convert a group of letters to words. 
There are various databases out there for this in different language i think. Maybe in spell checkers

**Comment by milosgajdos83** [comment]
What is ICE System?

Either way, I think there are better ways of doing OCR than Hopfield. Again, depends on use case.

**Comment by joeblew99** [comment]
fair enough.

I got it working anyway thanks
